name: Project ZK LITE Builder
on:
  workflow_dispatch:
    inputs:
      PLATFORM:
        description: "ANDROID VERSION"
        required: true
      ZK_VER:
        description: "ZK VERSION"
        required: true
      URL:
        description: "XIAOMI.EU ROM URL"
        required: true
        default: 'https://cdnorg.d.miui.com/OS2.0.5.0.VMRCNXM/marble-ota_full-OS2.0.5.0.VMRCNXM-user-15.0-360119838b.zip'
      IMAGE_TYPE:
          description: "IMAGE TYPE"
          required: true
          default: 'erofs'
          type: choice
          options:
          - erofs
          - ext4
      EXT_RW:
          description: 'EXT4 R/W'
          required: true
          type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Optimize environment
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: Check out repository files
        uses: actions/checkout@main
      - name: Prepare the required environment
        run: |
          sudo timedatectl set-timezone Asia/Ho_Chi_Minh
          sudo apt-get install python3 aria2 p7zip-full zstd
      - name: Building ROM
        run: |
          sudo bash "$GITHUB_WORKSPACE"/make.sh ${{ github.event.inputs.PLATFORM }} ${{ env.date }} $GITHUB_ENV $GITHUB_WORKSPACE ${{ github.event.inputs.URL }} ${{ github.event.inputs.IMAGE_TYPE }} ${{ github.event.inputs.EXT_RW }}
      - name: Processing ROM
        run: |
          mkdir -p "$GITHUB_WORKSPACE"/GithubRelease
          cd "$GITHUB_WORKSPACE"/GithubRelease
          sudo split -b 1536M -d "$GITHUB_WORKSPACE"/zip/"${{ env.NEW_PACKAGE_NAME }}" "${{ env.NEW_PACKAGE_NAME }}"
          cd "$GITHUB_WORKSPACE"
          touch file.log
          echo -e "移植版本: ${{ env.date }}\n底包版本: ${{ env.vendor_date }}" > file.log
      - name: Create Github Release
        uses: ncipollo/release-action@main
        with:
          artifacts: ${{ github.workspace }}/GithubRelease/*
          name: "${{ env.date }}"
          tag: "${{ env.date }}"
          bodyFile: "${{ github.workspace }}/file.log"
          allowUpdates: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
